version: '3'
services:
  nginx:
    image: nginx:lstest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/logs/nginx
    links:
      - php

  php:
    build: ./images/php
    links:
      - mysql
    volumes:
      - ./www:/var/www

