version: '2.14.2'
services:
  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/logs/nginx
    links:
      - php
    healthcheck:
      test: curl -f http://127.0.0.1:80 | grep works  || exit 1
      interval: 5s
      retries: 5
      start_period: 1s
      timeout: 1s   

  php:
    build: ./images/php
    volumes:
      - ./www:/var/www
    
